image: node

before_script:
  - npm install

build sass files:
  stage: build
  script:
    - npm run build

test css in own dir:
  stage: test
  script:
    - cd css/dev
    - CSS_DEV_FILES=$(find . -type f -name "*.css")
    - npx csslint $CSS_DEV_FILES
    - cd ../prod
    - CSS_PROD_FILES=$(find . -type f -name "*.css")
    - npx csslint $CSS_PROD_FILES

test all css:
  stage: test
  script:
    - npm run lint
  rules:
    - allow_failure: true