image: node

before_script:
  - npm install

build sass files:
  stage: build
  script:
    - npm run build

test css file usages:
  stage: test
  script:
    - cd css/dev
    - CSS_DEV_FILES=$(find . -type f -name "*.css")
    - cd ../prod
    - CSS_PROD_FILES=$(find . -type f -name "*.css")
    - cd ../..
    - echo $CSS_DEV_FILES
    - echo $CSS_PROD_FILES